<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <article class="container mt-5 mb-5">

        <h1 class="mb-5"><?= $title ?></h1>
        <div id="à-propos">
            <p>
                Bienvenue sur mon blog ! Je m’appelle Jean Forteroche et je suis un écrivain
                passionné.  J’ai récemment entrepris un nouveau projet excitant : l’écriture
                d’un roman intitulé "Billet simple pour l’Alaska".
            </p>
            <p>
                Ce roman raconte l’histoire d’un homme en quête d’aventure et de liberté, qui
                décide de tout quitter pour partir à la découverte de l’Alaska.  À travers les
                pages de ce livre, je souhaite partager avec vous les paysages grandioses, les
                rencontres inoubliables et les défis auxquels mon personnage principal sera
                confronté.
            </p>
            <p>
                Sur ce blog, vous pourrez suivre l’évolution de mon roman au fur et à mesure de
                son écriture.  Je publierai régulièrement les chapitres pour que vous puissiez
                les lire et les commenter.  J’espère que cette approche interactive vous
                permettra de vous plonger davantage dans l’histoire et de partager vos
                impressions avec moi.
            </p>
            <p>
                L’Alaska, avec sa nature sauvage et ses mystères, est un lieu fascinant qui
                offre une toile de fond parfaite pour mon histoire.  J’ai moi-même eu la chance
                de visiter cette région et j’ai été profondément marqué par sa beauté brute et
                sa capacité à nous reconnecter avec l’essentiel.
            </p>
            <p>
                J’espère que "Billet simple pour l’Alaska" vous transportera dans ce voyage
                unique, où les émotions seront fortes et les rebondissements nombreux.
                N’hésitez pas à me laisser vos commentaires et vos suggestions tout au long de
                cette aventure littéraire.
            </p>
            <p>
                Je vous souhaite une agréable lecture et je vous remercie de me suivre dans
                cette aventure !
            </p>
        </div>

        <div id="contact">
            <h2 class="h2 mt-5 mb-5"> Me contacter</h2>
            <p>
                Si vous souhaitez me contacter, n’hésitez pas à utiliser les informations
                ci-dessous :
            </p>

            <ul>
                <li>
                    Adresse e-mail : <a href="mailto:jean.forteroche@<?= $domain ?>">jean.forteroche@<?= $domain ?></a>
                </li>
                <li>
                    Réseaux sociaux : Vous pouvez me retrouver sur Twitter (<a href="https://twitter.com/JeanForteroche">@JeanForteroche</a>) et sur
                    Instagram (<a href="https://www.instagram.com/JeanForteroche">@JeanForteroche</a>) pour suivre mes actualités et échanger avec moi.
                </li>
            </ul>

            <p>
                Je serai ravi de répondre à vos questions, de discuter de mon roman ou de tout
                autre sujet qui vous intéresse.  N’hésitez pas à me contacter, je serai attentif
                à tous vos messages.
            </p>
        </div>
    </article>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
