<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <main class="container mt-5 mb-5">
        <form action="" method="post">
            <input name="article_title" type="text" class="form-control mb-3" placeholder="Titre">
            <textarea name="article_content" id="tinymce" placeholder="Article"></textarea>
            <button type="submit" class="btn btn-primary mt-3">Enregister l’article</button>
        </form>
    </main>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
