<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <main class="container mt-5 mb-5">
        <h1><?= $title ?></h1>
        <?php if (isset($form['auth_username']) || isset($form['auth_password'])) : ?>
            <div class="alert alert-danger">Mauvais nom d’utilisateur ou mauvais mot de passe !</div>
        <?php endif ?>
        <form class="mt-5" action="" method="post">
            <div class="form-group mb-3">
                <label for="auth_username">Nom d’utilisateur</label>
                <?php if (isset($form['auth_username'])) : ?>
                    <input name="auth_username"  type="text" class="form-control" placeholder="Nom d’utilisateur" value="<?= $form['auth_username'] ?>">
                <?php else : ?>
                    <input name="auth_username"  type="text" class="form-control" placeholder="Nom d’utilisateur">
                <?php endif ?>
            </div>
            <div class="form-group mb-3">
                <label for="auth_password">Mote de passe</label>
                <?php if (isset($form['auth_password'])) : ?>
                    <input name="auth_password"  type="password" class="form-control" placeholder="Mote de passe" value="<?= $form['auth_password'] ?>">
                <?php else : ?>
                    <input name="auth_password"  type="password" class="form-control" placeholder="Mote de passe">
                <?php endif ?>
            </div>
            <button type="submit" class="btn btn-primary">Se connecter</button>
        </form>
    </main>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
