<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <main class="container mt-5 mb-5">
        <header>
            <h1><?= $title ?></h1>
        </header>

        <?php foreach ($articles as $article) : ?>
            <div class="mt-5">
                <p>
                    <span class="h5"><?= $article->getTitle() ?></span>
                    <br>
                    <small>
                        <time datetime="<?= $article->getInsertedAt(true)->format('Y-m-d') ?>">
                            <?= $article->getInsertedAt(true)->format('d/m/Y') ?>
                        </time>
                    </small>
                </p>
                <a href="<?= $url ?>/article/<?= $article->getId() ?>" class="btn btn-outline-primary btn-sm">Lire l’article</a>
            </div>
        <?php endforeach ?>
    </main>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
