<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <main class="container mt-5 mb-5">
        <header>
            <h1><?= $article->getTitle() ?></h1>
            <p>
                <small>
                    <?php if ($article->getModifiedAt(true) > $article->getInsertedAt(true)) : ?>
                        <div>
                            Modifié le <time datetime="<?= $article->getModifiedAt(true)->format('Y-m-d') ?>"><?= $article->getModifiedAt(true)->format('d/m/Y') ?></time>
                        </div>
                    <?php else : ?>
                        <div>
                            Ajouté le <time datetime="<?= $article->getInsertedAt(true)->format('Y-m-d') ?>"><?= $article->getInsertedAt(true)->format('d/m/Y') ?></time>
                        </div>
                    <?php endif ?>
                </small>
            </p>
        </header>

        <article class="mt-5 mb-5"><?= $article->getContent() ?></article>

        <footer class="pt-3">
            <?php if ($article->getComments()) : ?>
                <?php foreach ($article->getComments() as $comment) : ?>
                    <?php if (!$comment->getIsFlagged()) : ?>
                        <div class="card bg-light-subtle mb-3">
                            <div class="card-header">
                                <b><?= htmlspecialchars($comment->getName()) ?></b>
                                <br>
                                <small>
                                    <time datetime="<?= $comment->getInsertedAt(true)->format('Y-m-d') ?>"><?= $comment->getInsertedAt(true)->format('d/m/Y') ?></time>
                                </small>
                            </div>
                            <div class="card-body">
                                <p class="cart-text"><?= htmlspecialchars($comment->getContent()) ?></p>
                                <a href="<?= $url ?>/signaler/<?= $comment->getId() ?>" class="btn btn-outline-danger btn-sm">Signaler</a>
                            </div>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            <?php endif ?>
        </footer>


    </main>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
