<?php include_once(__DIR__ . '/../Partials/head.phtml'); ?>

<body>

    <?php include_once(__DIR__ . '/../Partials/header.phtml'); ?>

    <main class="container mt-5 mb-5">
        <header>
            <h1><?= $article->getTitle() ?></h1>
            <p>
                <small>
                    <?php if ($article->getModifiedAt(true) > $article->getInsertedAt(true)) : ?>
                        <div>
                            Modifié le <time datetime="<?= $article->getModifiedAt(true)->format('Y-m-d') ?>"><?= $article->getModifiedAt(true)->format('d/m/Y') ?></time>
                        </div>
                    <?php else : ?>
                        <div>
                            Ajouté le <time datetime="<?= $article->getInsertedAt(true)->format('Y-m-d') ?>"><?= $article->getInsertedAt(true)->format('d/m/Y') ?></time>
                        </div>
                    <?php endif ?>
                </small>
            </p>
        </header>

        <article class="mt-5 mb-5"><?= $article->getContent() ?></article>

        <footer class="pt-3">
            <div>
                <?php if ($article->getComments()) : ?>
                    <?php foreach ($article->getComments() as $comment) : ?>
                        <?php if (!$comment->getIsFlagged()) : ?>
                            <div class="card bg-light-subtle mb-3">
                                <div class="card-header">
                                    <b><?= htmlspecialchars($comment->getName()) ?></b>
                                    <br>
                                    <small>
                                        <time datetime="<?= $comment->getInsertedAt(true)->format('Y-m-d') ?>"><?= $comment->getInsertedAt(true)->format('d/m/Y') ?></time>
                                    </small>
                                </div>
                                <div class="card-body">
                                    <p class="cart-text"><?= htmlspecialchars($comment->getContent()) ?></p>
                                    <a href="<?= $url ?>/signaler/<?= $comment->getId() ?>" class="btn btn-outline-danger btn-sm">Signaler</a>
                                </div>
                            </div>
                        <?php endif ?>
                    <?php endforeach ?>
                <?php endif ?>
            </div>

            <div class="card bg-light-subtle border border-primary">
                <div class="card-header bg-light">Commenter</div>
                <form class="card-body" action="<?= \App\Model\Url::build('commenter', $article->getId()) ?>" method="post">
                    <?php if (isset($_GET['comment_name']) && empty($_GET['comment_name'])) : ?>
                        <div class="alert alert-danger">Renseignez votre nom ou un pseudo !</div>
                    <?php endif ?>
                    <?php if (isset($_GET['comment_email']) && empty($_GET['comment_email'])) : ?>
                        <div class="alert alert-danger">Renseignez une adresse email valide !</div>
                    <?php endif ?>
                    <?php if (isset($_GET['comment_content']) && empty($_GET['comment_content'])) : ?>
                        <div class="alert alert-danger">Le commentaire est vide !</div>
                    <?php endif ?>
                    <div class="form-group mb-3">
                        <label for="comment_name">Nom ou pseudonyme</label>
                        <input name="comment_name"  type="text" class="form-control" placeholder="Nom ou pseudonyme" value="<?= $_GET['comment_name'] ?? null ?>">
                    </div>
                    <div class="form-group mb-3">
                        <label for="comment_email">Adresse email</label>
                        <input name="comment_email"  type="text" class="form-control" placeholder="Adresse email" value="<?= $_GET['comment_email'] ?? null ?>">
                    </div>
                    <div class="form-group mb-3">
                    <label for="comment_content">Commentaire</label>
                        <textarea name="comment_content" class="form-control" placeholder="Commentaire" rows="5"><?= $_GET['comment_content'] ?? null ?></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Commenter</button>
                </form>
            </div>
        </footer>


    </main>

    <?php include_once(__DIR__ . '/../Partials/footer.phtml'); ?>

    <?php include_once(__DIR__ . '/../Partials/script.phtml'); ?>

</body>
