<header>
    <nav class="navbar navbar-expand-sm bg-primary-subtle p-3">
        <div class="container">
            <b class="font-weight-bold text-uppercase">
                <a class="navbar-brand" href="<?= $url ?>">
                    <?= $domain ?>
                </a>
            </b>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Menu de navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="à-propos">À propos</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="à-propos#contact">Contact</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
</header>
